[project]
name = "yet-another-python-project-template"
version = "0.1.0"
description = "Python project template"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = []

[dependency-groups]
dev = ["copier==9.4.1", "copier-templates-extensions>=0.3.0"]
